env: development
src: _project
dist: project
cache: true
ibooks_specified_fonts: true
theme: b-ber-theme-serif
themes_directory: ./themes
base_url: "/"
base_path: /
remote_url: "https://wileywiggins.com/obelisk_reader"
reader_url: 'https://wileywiggins.com/obelisk_reader/project-reader'
downloads:
  - label: Download as Epub
    description: Obelisk Manual
    url: >-
      https://wileywiggins.com/obelisk_reader/339e849a459ca89b707c93e7fd6e508f3e2ecf6f.epub
  - label: Download as PDF
    description: Obelisk Manual
    url: >-
      https://wileywiggins.com/obelisk_reader/Obelisk_User's_Manual_Book_of_Secrets-Amplexxus.pdf
    

pdf_options:
  paper_size: a5
  pdf_page_numbers: true
  pdf_page_margin_top: 25
  pdf_page_margin_right: 25
  pdf_page_margin_bottom: 25
  pdf_page_margin_left: 25

ui_options:
  navigation:
    header_icons:
      info: true
      home: false
      downloads: true
      toc: true
    footer_icons:
      chapter: true
      page: true
private: true
ignore: []
autoprefixer_options:
  overrideBrowserslist:
    - last 2 versions
    - '> 2%'
  flexbox: no-2009
layout: columns
group_footnotes: true
