env: development
src: _project
dist: project
cache: true
ibooks_specified_fonts: true
theme: b-ber-theme-serif
themes_directory: ./themes
base_url: 'http://localhost:4000/project-web'
base_path: /
downloads:
  - label: Download as Epub
    title: b-ber All Directives Demo
    url: >-
      https://wileywiggins.com/obelisk-reader/339e849a459ca89b707c93e7fd6e508f3e2ecf6f.epub
  - label: Download as Mobi
    title: b-ber All Directives Demo
    url: >-
      https://wileywiggins.com/obelisk-reader/339e849a459ca89b707c93e7fd6e508f3e2ecf6f.mobi
ui_options:
  navigation:
    header_icons:
      info: true
      home: true
      downloads: true
      toc: true
    footer_icons:
      chapter: true
      page: true
private: false
ignore: []
autoprefixer_options:
  overrideBrowserslist:
    - last 2 versions
    - '> 2%'
  flexbox: no-2009
layout: columns
group_footnotes: true
