env: development
src: _project
dist: project
cache: true
ibooks_specified_fonts: true
theme: b-ber-theme-serif
themes_directory: ./themes
base_url: 'https://wileywiggins.com/'
base_path: '/obelisk_reader/project-reader/'
reader_url: 'https://wileywiggins.com/obelisk_reader/project-reader/'
remote_url: 'https://wileywiggins.com/'
downloads:
  - label: Download as Epub
    title: Obelisk Manual
    url: >-
      https://wileywiggins.com/obelisk_reader/339e849a459ca89b707c93e7fd6e508f3e2ecf6f.epub
ui_options:
  navigation:
    header_icons:
      info: true
      home: true
      downloads: true
      toc: true
    footer_icons:
      chapter: true
      page: true
private: false
ignore: []
autoprefixer_options:
  overrideBrowserslist:
    - last 2 versions
    - '> 2%'
  flexbox: no-2009
layout: columns
group_footnotes: true
